### PR TITLE
Merge pull request #1 from anandbibek/master

### PR DESCRIPTION
**Pull request by RRDD098**
material design

### CODE REVIEW

**Comment by RRDD098** [comment]
request send

**Comment by anandbibek** [comment]
What do you want to ask about material design?

**Comment by anandbibek** [comment]
There is no change. You've to add your own details in file of your own name

**Comment by RRDD098** [comment]
is the app ll be design with material design?

On Fri, Dec 18, 2015 at 10:55 AM, Ananda Bibek Ray <notifications@github.com

**Pull request closed without merging**
